version: '3'
services:
  streamlit_app:
    build: .
    command: streamlit run src/main.py --server.port 8080
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - LISTEN_PORT=8080
    restart: unless-stopped
